//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LFishkel.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.Movements = new HashSet<Movement>();
        }
    
        public int Id { get; set; }
        public int PersonId { get; set; }
        public int BankId { get; set; }
    
        public virtual ICollection<Movement> Movements { get; set; }
        public virtual Bank Bank { get; set; }
        public virtual Person Person { get; set; }
    }
}
